import { Link } from 'react-router-dom'

export function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <div className="max-w-[720px] mx-auto px-4 md:px-6 py-16 md:py-24">
        <Link to="/" className="text-[14px] text-[#6B7280] hover:text-[#1A1A1A] font-medium mb-8 inline-block">
          Back to Toolstoy
        </Link>
        <h1 className="font-bold text-[36px] text-[#1A1A1A]">Terms of Service</h1>
        <p className="mt-2 text-[14px] text-[#6B7280]">Last updated: February 2026</p>

        <div className="mt-10 space-y-6 text-[15px] text-[#1A1A1A] leading-[1.7]">
          <section>
            <h2 className="font-semibold text-[18px] mb-2">1. Agreement to Terms</h2>
            <p>
              By accessing and using Toolstoy (&quot;Service&quot;), you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service.
            </p>
          </section>

          <section>
            <h2 className="font-semibold text-[18px] mb-2">2. Description of Service</h2>
            <p>
              Toolstoy is a B2B SaaS platform that enables merchants to create AI-powered animated characters from their e-commerce products. These characters can be embedded on websites as interactive chat assistants.
            </p>
          </section>

          <section>
            <h2 className="font-semibold text-[18px] mb-2">3. User Accounts and Registration</h2>
            <p>
              You must provide accurate and complete registration information. You are responsible for maintaining the confidentiality of your account credentials. You must notify us immediately of any unauthorized use of your account.
            </p>
          </section>

          <section>
            <h2 className="font-semibold text-[18px] mb-2">4. Subscription Plans and Payment</h2>
            <p>
              Toolstoy offers various subscription plans with different features and usage limits. Subscription fees are billed in advance on a monthly or annual basis. All fees are non-refundable except as required by law. We reserve the right to change pricing with 30 days notice.
            </p>
          </section>

          <section>
            <h2 className="font-semibold text-[18px] mb-2">5. Acceptable Use</h2>
            <p>
              You may use Toolstoy for legitimate business purposes only. You agree not to:
            </p>
            <ul className="list-disc list-inside mt-2 space-y-1">
              <li>Use the service for any illegal or unauthorized purpose</li>
              <li>Create characters that violate third-party rights</li>
              <li>Generate harmful, offensive, or inappropriate content</li>
              <li>Attempt to reverse engineer or circumvent security measures</li>
              <li>Use the service to spam, harass, or harm others</li>
            </ul>
          </section>

          <section>
            <h2 className="font-semibold text-[18px] mb-2">6. Intellectual Property Rights</h2>
            <p>
              You retain ownership of your product data and the characters you create. By using Toolstoy, you grant us a limited, non-exclusive license to process, store, and use your data solely to provide the service. Toolstoy retains all rights to our software, technology, and brand.
            </p>
          </section>

          <section>
            <h2 className="font-semibold text-[18px] mb-2">7. AI-Generated Content</h2>
            <p>
              Characters and responses are generated by AI systems. You acknowledge that AI-generated content may not always be accurate and you are responsible for reviewing and editing content before deployment. We are not liable for AI-generated content.
            </p>
          </section>

          <section>
            <h2 className="font-semibold text-[18px] mb-2">8. Service Availability and Support</h2>
            <p>
              We strive to maintain high service availability but do not guarantee uninterrupted service. We may perform maintenance that temporarily affects availability. Support is provided via email for paid plans.
            </p>
          </section>

          <section>
            <h2 className="font-semibold text-[18px] mb-2">9. Termination</h2>
            <p>
              You may terminate your account at any time. We may suspend or terminate your account for violation of these terms. Upon termination, your right to use the service ceases immediately, but all obligations remain.
            </p>
          </section>

          <section>
            <h2 className="font-semibold text-[18px] mb-2">10. Disclaimers and Limitation of Liability</h2>
            <p>
              The service is provided &quot;as is&quot; without warranties of any kind. We disclaim all warranties, express or implied. Our total liability shall not exceed the amount paid by you in the 12 months preceding the claim. We are not liable for indirect, incidental, or consequential damages.
            </p>
          </section>

          <section>
            <h2 className="font-semibold text-[18px] mb-2">11. Indemnification</h2>
            <p>
              You agree to indemnify and hold harmless Toolstoy from any claims, damages, or expenses arising from your use of the service or violation of these terms.
            </p>
          </section>

          <section>
            <h2 className="font-semibold text-[18px] mb-2">12. Governing Law</h2>
            <p>
              These terms shall be governed by and construed in accordance with the laws of the jurisdiction where Toolstoy operates, without regard to conflict of law principles.
            </p>
          </section>

          <section>
            <h2 className="font-semibold text-[18px] mb-2">13. Changes to Terms</h2>
            <p>
              We reserve the right to modify these terms at any time. Changes will be effective upon posting. Your continued use of the service constitutes acceptance of any changes.
            </p>
          </section>

          <section>
            <h2 className="font-semibold text-[18px] mb-2">14. Contact Information</h2>
            <p>
              Questions about these terms? Contact us at{' '}
              <a href="mailto:legal@toolstoy.app" className="text-[#1A1A1A] underline hover:no-underline">
                legal@toolstoy.app
              </a>
            </p>
          </section>
        </div>
      </div>
    </div>
  )
}
